### ISSUE TITLE
CI-Testing with online staged servers

### ISSUE THREAD

**Issue by hpk42** [chatmail/relay#100]
right now, the CI does not try to fully setup a fresh machine.  

We discussed to configure one dedicated VM that CI tasks can acquire and use for setting up,
ideally also including our generated DNS setup.  To not interfere with real-world systems,
it's probably best to have the CI domain on something else than ".testrun.org" because testrun is actually used in production by users and automatically messging around with DNS there is probably not a good idea.

**Comment by missytake** [comment]
Proposal:

have a GitHub action, which runs on every push to the main branch:

- rebuild the VPS with a clean Debian/Ubuntu image: https://docs.hetzner.cloud/#server-actions-rebuild-a-server-from-an-image
  - staging.testrun.org should point to this VPS
  - optional: run two jobs with both images
- run `cmdeploy run staging.testrun.org`
- run `cmdeploy test`
- run `cmdeploy run nine.testrun.org`

Unfortunately, the Hetzner API doesn't seem to offer scoped API tokens which only give access to one VM or so. I just see the option to generate a general token: https://docs.hetzner.com/cloud/api/getting-started/generating-api-token/
We could use a dedicated Hetzner account for the staging.testrun.org VPS though (mine for example).

**Comment by missytake** [comment]
We could also make this automatically deploy to nine.testrun.org, after all tests against staging.testrun.org pass, and should probably run `cmdeploy test` again afterwards, as the CI only tests a completely fresh machine, while nine.testrun.org might still have some older remnants around.

We could also create a second non-reset VPS for CI, to test deployment on machines with old remnants before we deploy it to nine.

**Comment by missytake** [comment]
CI takes over 8 minutes, so it's not something we can run on every commit I'd say. Right now it's only executed when we push to main, so only *after* merging a PR. This is meant to ensure that deployment to nine.testrun.org will not break anything, before we deploy it.

**Comment by hpk42** [comment]
I think it's fine to not automatically deploy to nine.testrun.org,
maybe even preferable as doing it conciously means that one can 
also run tests and see a bit if anything apparently breaks. 
It may be helpful, however, to deploy-update master-merges to a dedicated
CI-service used by dc-core CI (which would then not use nine anymore). 
Merging automatically to a dedicated CI machine would mean that we would
relatively quickly notice any break with Delta Chat usage (securejoin etc.) 
because those tests are often run in core's CI. 
But this dedicated CI-machine suggestion is not neccessary for merging this PR.

**Comment by missytake** [comment]
Alternatively - we could limit concurrent CI runs so there is only one CI job at the same time, re-introduce resetting the VPS, and run it on every commit in a PR: https://stackoverflow.com/questions/74033010/how-can-i-prevent-a-github-action-from-running-in-parallel-for-the-same-branch

Then we could also use it in PRs.
