### ISSUE TITLE
Creating an account via QR code randomly failed

### ISSUE THREAD

**Issue by link2xt** [chatmail/relay#128]
I thought it is because generated account started with a number.
I got this failure from scanning a `nine.testrun.org` QR code:
```
25786.1s [D]core/event: ConfigureProgress 95 {
  comment: 'Configuration failed. Error: Cannot login as "58k34gfrr@nine.testrun.org". Please check if the e-mail address and the password are correct.\n' +
    '\n' +
    'no response: code: None, info: Some("[AUTHENTICATIONFAILED] Authentication failed.")',
  kind: 'ConfigureProgress',
  progress: 0
```

**Comment by missytake** [comment]
The addr doesn't exist:
```
sqlite> SELECT * FROM users where addr="58k34gfrr@nine.testrun.org";
sqlite> 
```

**Comment by sysfu** [comment]
> This is probably an issue with doveauth interaction with SQLite failing for some reason, but we need logs for this. Or core could just try twice.

Similar issue happened with a friend of mine I was onboarding about an hour ago. He tried a 2nd time and it worked.

**Comment by hpk42** [comment]
Just has a friend trying to.create a nine account, only the third attempt worked. Before there were login errors.  So this issue is real. Account creation is flaky.
