### ISSUE TITLE
Make it possible to uninstall

### ISSUE THREAD

**Issue by link2xt** [chatmail/relay#131]
Currently we install packages, configs and venvs in all kinds of places.

Of course chatmail should run on a dedicated (virtual) machine, but having some overview of where things are is always nice.

Maybe move everything possible into /opt/chatmail/ or so, including postfix and dovecot configs, and generate our own systemd units for postfix and dovecot so we run them with configs in non-standard locations and do not overwrite existing configs?

**Comment by hpk42** [comment]
for now, it sounds a bit like "nice to have" or do you have any particular real-need in mind for this?
