### ISSUE TITLE
Going directly to https://nine.testrun.org/cgi-bin/newemail.py shows JSON in a browser

### ISSUE THREAD

**Issue by link2xt** [chatmail/relay#162]
During testing of nine.testrun.org user scanned QR code from the website with a browser (IIRC it was a Brave browser) and ended up with a browser showing JSON directly, even though Delta Chat was installed on the phone. Clicking on the QR code in a browser worked.

We need to reproduce this and find a way to deal with the problem, probably redirecting to `dcaccount:` URL if we detect a browser request.

**Comment by missytake** [comment]
The only explanation I can come up with is that brave's QR code scanner doesn't respect the OS-registered URL schemes and tries to search for it? I can't think of a way how we could interject there, a redirect wouldn't solve this, as the HTTP requests go to https://search.brave.com.
