### ISSUE TITLE
Messages from mailing lists fail DKIM checks

### ISSUE THREAD

**Issue by link2xt** [chatmail/relay#177]
Since #20 is merged mails from hispanilandia.net users to nine.testrun.org pass (according to @adbenitez), but mailing list messages are rejected as they fail `R_DKIM_REJECT`. I have checked the mails, they actually contain two DKIM signatures, original one and hispanilandia.net one. Ideally hispanilandia.net signature should be ok and the check pass, but this does not happen for some reason.

**Comment by hpk42** [comment]
On Sun, Jan 14, 2024 at 12:19 -0800, link2xt wrote:
> Since #20 is merged mails from hispanilandia.net users to nine.testrun.org pass (according to @adbenitez), but mailing list messages are rejected as they fail `R_DKIM_REJECT`. I have checked the mails, they actually contain two DKIM signatures, original one and hispanilandia.net one. Ideally hispanilandia.net signature should be ok and the check pass, but this does not happen for some reason.

Do hispanilandia anonymizing ML mails contain any valid DKIM sig or not?
