### ISSUE TITLE
Replace rspamd SPF/DKIM/DMARC with a filter checking DKIM and From: domain alignment

### ISSUE THREAD

**Issue by link2xt** [chatmail/relay#179]
Currently we use rspamd with [force actions](https://rspamd.com/doc/modules/force_actions.html) module to reject all emails that don't have a valid DKIM signature (#20, #176). If email has a valid DKIM signature, checking SPF and DMARC does not add anything and even resolving additional DNS records for this is not worth it.

Unless we have to revert this DKIM check because it causes too much trouble, we can replace `rspamd` with our own SMTP filter in Python using https://pypi.org/project/dkimpy/ It is maintained at https://git.launchpad.net/dkimpy/ and can verify as well as sign DKIM. So we can sign DKIM using this library in filtermail and check DKIM in a new incoming filter that we will need anyway if we want to start doing push notifications.

We can still keep `rspamd` for DKIM signing or restore OpenDKIM, DKIM-signing is independent. `rspamd` is good enough for this, it even signs Autocrypt headers out of the box.

**Comment by missytake** [comment]
Yes, I guess this does make sense. It is more exact in its purpose of preventing FROM forgery than the rest of the DMARC standard.

We might need additional measures to stop SMTP smuggling then, not sure I correctly understand the attack vector right now.

**Comment by missytake** [comment]
> There are other interesting things we can do with our own incoming filter, e.g. support [RRVS](https://datatracker.ietf.org/doc/html/rfc7293) in Delta Chat to make sure emails are not delivered to wrong recipient if the server is resetup without a backup and there is a chance someone takes over the mailbox with a new password.

slightly off-topic, but I'm not sure about RRVS:

- it adds unencrypted metadata which might help attackers identify an account if connected with other data
- end-to-end encryption is more useful in preventing recipients from reading messages they ought not to receive

In case it's actually the same person using the deleted-and-recreateed account, we wouldn't want to drop the message silently. They might still have the private key to decrypt it, then great, they can reply, no one notices there was a hiccup. If they don't have the private key anymore, they can ask the sender to re-send the message. If they are indeed a different person but still ask the sender to re-send the message, the sender at least gets a "Setup changed" error message and can ask the recipient over a different channel if they still have control over that mailbox.

I think RRVS wouldn't improve on the current situation, it raises hard-to-understand errors, but not in the right situations.
