### ISSUE TITLE
Is TLSRPTv1 record useful?

### ISSUE THREAD

**Issue by link2xt** [chatmail/relay#181]
It was added in 5305dfab12bef0a3ae30592ff9f07d9576923605 from PR #75.

Do we even receive any reports, is it supported by other providers?

We should probably unsubscribe from reports if we receive them, similarly to #180

**Comment by missytake** [comment]
> We receive reports from [noreply-smtp-tls-reporting@google.com](mailto:noreply-smtp-tls-reporting@google.com), [tlsrpt-noreply@microsoft.com](mailto:tlsrpt-noreply@microsoft.com) etc.

I looked at those reports, they don't have an attachment, the only unique thing about them is some ID of a mail? Not sure what this should be useful for.
