### ISSUE TITLE
Consider switching to always softfailing SPF policy

### ISSUE THREAD

**Issue by link2xt** [chatmail/relay#211]
Current policy looks like `"v=spf1 a:nine.testrun.org -all"`. This means that combined with our DMARC policy `"v=DMARC1;p=reject;adkim=s;aspf=s"` the mail will still be accepted as sent from nine.testrun.org if it originates from nine.testrun.org IP address.

Because the strictest DMARC policy means SPF *or* DKIM pass, the only way to enforce DKIM is to make SPF always softfail. We can publish a `"v=spf1 ~all"` for this. Note that hardfail is not recommended as it might result in rejection even before the mail reaches DMARC checks: https://www.mailhardener.com/blog/why-mailhardener-recommends-spf-softfail-over-fail

One concern is that it might break delivery to servers running OpenSPF without any DMARC implementation, but this should be rare and we probably don't care about sending messages to such servers as they will likely not implement DKIM and not be able to reply anyway.

Sidenote: At DMARC WG mailing list there is a recent discussion about adding explicity DKIM required policy, but it will likely be rejected and even if it somehow gets into RFC I doubt it will be adopted: https://mailarchive.ietf.org/arch/msg/dmarc/QKTkdwWKdrCIL_wR1kH7-2XwMPM/

**Comment by hpk42** [comment]
Sounds good, let go for SPF  Softail.
