### ISSUE TITLE
Echobot is running as root in root

### ISSUE THREAD

**Issue by link2xt** [chatmail/relay#256]
Echobot service currently starts echobot as root and without working directory, so it sets up its account directory in `/accounts`.

We should run it as separate user with working directory in `/home/echobot`.

The problem with redeploying echobot is that it generates new password on deployment and takes the name first time it starts. I suggest that instead of allowing anyone to take "echo" username in
https://github.com/deltachat/chatmail/blob/c640087498f891dd51d74dac9912f9fbd5d8a7b3/chatmaild/src/chatmaild/doveauth.py#L53
we place "echo" password into chatmail.ini and then both bot and doveauth take it from there.

**Comment by hpk42** [comment]
what's the status of this? I saw #259 got merged but this issue is still open?
