### ISSUE TITLE
Add setting for metrics endpoint

### ISSUE THREAD

**Issue by link2xt** [chatmail/relay#328]
Currently metrics are exposed over https under `/metrics`, but without any authentication. Metrics are generated with a cronjob. Current approach to metric generation is very limited, we have #183 open for exposing disk space and https://github.com/deltachat/chatmail/issues/273#issuecomment-2182007216

Since we want more dynamic metrics and expose data such as disk space that should not be publicly available, we will need to expose them over TCP and only to secure network, e.g. wireguard one.

By default we can expose metrics to `localhost:9123` or something like this. Someone who wants to monitor chatmail instance can then create a VPN (e.g. wireguard) interface and point the metrics server there to be collected with prometheus on the other side.

**Comment by hpk42** [comment]
not sure i fully understand but can you do a PR to produce mtail data?  

Does nine have a wireguard setup and if so, where is it documented?
