### ISSUE TITLE
dovecot: LMTP hardlinking is not working

### ISSUE THREAD

**Issue by link2xt** [chatmail/relay#339]
LMTP is supposed to deliver message once for the first recipient, then hardlink or copy the message to other recipients. As in typical chatmail setup all mailboxes reside on the same filesystem and owned by the same user and group, delivered mails should be hardlinked. However, it is not the case, `stat` command shows "Links: 1" for all delivered mails.

Apparently it is the problem caused by Sieve which is used for message notifications: https://dovecot.dovecot.narkive.com/qfq7puPs/maildir-hardlinks-with-sieve

**Comment by hpk42** [comment]
Thanks for investigating. The linked issue seems to indicate that it's not going to be fixed.  What is this issue about then?

**Comment by hpk42** [comment]
I don't think restoring a file would be a big issue .... It would get removed after twenty days anyways.  And it's only a hard link so not really taking up real disc space.

**Comment by missytake** [comment]
Getting rid of sieve doesn't sound like a problem - we don't use it anyway, right?
